#!/usr/bin/env bash
timestamp=$(date +%Y%m%d%H%M)

# Esto es magia arcana con arrays de bash
hosts=($(/guifibages/sbin/list-st))
limit=$(( ${#hosts[*]}-2 ))

function cagonla {
  echo $* >&2
  exit -1
}

for i in `seq 0 2 $limit`
do
  hostname=${hosts[$i]}
  ip=${hosts[$(($i+1))]}
  backupdir=/guifibages/backup/st/$hostname
  backupfile=$backupdir/$hostname-$timestamp.export
  [ -d backupdir ] || mkdir -p $backupdir || cagonla No es pot crear el directori $backupdir

  echo "$timestamp Fent backup de $hostname $ip"
  lastfile=$backupdir/$(ls -t $backupdir| head -1)
  ssh -o StrictHostKeyChecking=no guest@$ip /export compact > $backupfile || echo "Error al fer export de $hostname ($ip)" >&2

  # Si son iguals, crear un enlla√ fort. Ignorar 27 primers bytes (data de backup)

  if cmp -s -i 27 $lastfile $backupfile
  then
    echo "** Sense modificacions"
    ln -f $lastfile $backupfile
  fi
done
