#!/usr/bin/env bash
timestamp=$(date +%Y%m%d%H%M)

zona=${1:-bages}
function cagonla {
  echo $* >&2
  exit -1
}

for i in `./zoneinfo.py -f csv -s $zona`
do
  hostname=$(echo $i | awk -F, '{print $2}')
  ip=$(echo $i | awk -F, '{print $3}')
  backupdir=/guifibages/backup/st/$hostname
  backupfile=$backupdir/$hostname-$timestamp.export
  [ -d backupdir ] || mkdir -p $backupdir || cagonla No es pot crear el directori $backupdir

  echo "$timestamp Fent backup de $hostname $ip $lastfile $backupfile"
  lastfile=$backupdir/$(ls -t $backupdir| head -1)
  ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no guest@$ip /export compact > $backupfile || echo "Error al fer export de $hostname ($ip)" >&2

  # Si son iguals, crear un enlla√ fort. Ignorar 27 primers bytes (data de backup)

  if cmp -s -i 27 $lastfile $backupfile
  then
    echo "** Sense modificacions"
    ln -f $lastfile $backupfile
  fi
done
